### ISSUE TITLE
Protos should be built using NPM / Yarn install

### ISSUE THREAD

**Issue by weizenberg** [Yomanz/Kubets#2]
Currently, the Request and Response protos not generated, and not found in the typescript definitions.
The proto files should be generated using the `build:proto` command using the NPM / Yarn install command.

Also, the `protoc-gen-grpc` package should be installed as a dev dependency to allow this.

**Comment by Yomanz** [comment]
Closed in https://github.com/Yomanz/Kubets/commit/8b8ddf6295d9655142ccc26aa3a701f63066f3d4
